JobsParana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.shortcuts import redirect
from django.urls import path

from core.views import JobListView, MyProfileView, MyCurriculumView, JobDetailView, \
    UserRegistrationView, MyAddressDetailView, MyQualificationsDetailView, MyExperienceDetailView, MyProfileDetailView, \
    MyApplicationDetailView, SearchView, MyExperienceListView, MyApplicationsListView, MyQualificationsListView

app_name = 'core'

urlpatterns = [
    path('', lambda request: redirect('core:jobs'), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('jobs/', JobListView.as_view(), name='jobs'),
    path('jobs/<pk>/detail/', JobDetailView.as_view(), name='job_detail'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('profile/registration/', UserRegistrationView.as_view(), name='registration'),
    path('curriculum/', MyCurriculumView.as_view(), name='curriculum'),
    path('curriculum/<pk>/profile/', MyProfileDetailView.as_view(), name='curriculum_profile'),
    path('curriculum/<pk>/address/', MyAddressDetailView.as_view(), name='curriculum_address'),
    path('curriculum/<id>/qualifications/', MyQualificationsListView.as_view(), name='curriculum_qualifications'),
    path('curriculum/qualifications/<pk>/detail/', MyQualificationsDetailView.as_view(),
         name='curriculum_qualifications_detail'),
    path('curriculum/<id>/experiences/', MyExperienceListView.as_view(), name='curriculum_experiences'),
    path('curriculum/experiences/<pk>/detail/', MyExperienceDetailView.as_view(),
         name='curriculum_experiences_detail'),
    path('applications/<id>/', MyApplicationsListView.as_view(), name='applications'),
    path('applications/<pk>/detail/', MyApplicationDetailView.as_view(), name='application_detail'),
]

templates/candidates/applications/detail.html
{% extends '_base.html' %}
{% load custom_tags %}
{% load static %}

{% block title %} {{ application.job.title }} {% endblock %}

{% block content %}

    <section class="box">

        <div class="box__header p-2">
            <span># {{ application.job.id_job }}</span>

            <div>

                {% if application.job.is_pcd %}
                    <span class="tag-danger">Exclusivo PCD</span>
                {% endif %}

                {% if application.job.is_urgent %}
                    <span class="tag-danger">Urgente</span>
                {% endif %}

            </div>

        </div>

        <div class="box__center">

            <div class="box__content">

                <div class="box__information">

                    <label class="box__information-label">Requísitos</label>
                    <div class="box__information-content">{{ application.job.requirements | linebreaks }}</div>

                </div>

                <div class="box__information">

                    <label class="box__information-label">Horários</label>
                    <div class="box__information-content">{{ application.job.time_scale }}</div>

                </div>

                <div class="box__information">

                    <label class="box__information-label">Localização</label>
                    <div class="box__information-content">{{ application.job.company.district }}
                        - {{ application.job.company.city }}</div>

                </div>

                <div class="box__information">

                    <label class="box__information-label">Remuneração</label>
                    <div class="box__information-content">R$ {{ application.job.remuneration }}</div>

                </div>

            </div>

            <div class="box__main">

                <ol class="stepper__container-vertical" data-stepper-status='{{ application.status }}' id="stepper_id">

                    <li class="stepper__item-vertical">       
                    
                        <span class="stepper__item stepper__item-default" id="step-1">
                            <svg class="stepper__icon" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 12">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                          stroke-width="2"
                                          d="M1 5.917 5.724 10.5 15 1.5"></path>
                            </svg>
                        </span>

                        <h3 class="stepper__item-title">Confirmada</h3>
                        <p class="text-sm">Recebemos sua candidatura com sucesso, aguarde as próximas etapas do
                            processo.</p>

                    </li>

                    <li class="stepper__item-vertical">
                        
                        <span class="stepper__item stepper__item-default" id="step-2">
                            <svg class="stepper__icon" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 16">
                                <path d="M18 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2ZM6.5 3a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5ZM3.014 13.021l.157-.625A3.427 3.427 0 0 1 6.5 9.571a3.426 3.426 0 0 1 3.322 2.805l.159.622-6.967.023ZM16 12h-3a1 1 0 0 1 0-2h3a1 1 0 0 1 0 2Zm0-3h-3a1 1 0 1 1 0-2h3a1 1 0 1 1 0 2Zm0-3h-3a1 1 0 1 1 0-2h3a1 1 0 1 1 0 2Z"></path>
                            </svg>
                        </span>

                        <h3 class="stepper__item-title">Revisão</h3>
                        <p class="text-sm">Nessa etapa a equipe irá revisar e validar seu currículo.</p>

                    </li>

                    <li class="stepper__item-vertical">
                       
                        <span class="stepper__item stepper__item-default" id="step-3">
                            <svg class="stepper__icon" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                                <path d="M16 1h-3.278A1.992 1.992 0 0 0 11 0H7a1.993 1.993 0 0 0-1.722 1H2a2 2 0 0 0-2 2v15a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2Zm-3 14H5a1 1 0 0 1 0-2h8a1 1 0 0 1 0 2Zm0-4H5a1 1 0 0 1 0-2h8a1 1 0 1 1 0 2Zm0-5H5a1 1 0 0 1 0-2h2V2h4v2h2a1 1 0 1 1 0 2Z"></path>
                            </svg>
                         </span>

                        <h3 class="stepper__item-title">Entrevista</h3>
                        <p class="text-sm">Caso seja selecionado entraremos em contato para conhecer melhor você.</p>
                    </li>

                    <li class="stepper__item-vertical-last">

                        {% if application.status == "Não Selecionada" %}

                            <span class="stepper__item stepper__item-danger">
                            
                                <svg class="stepper__icon" aria-hidden="true"
                                     xmlns="http://www.w3.org/2000/svg" fill="none"
                                     viewBox="0 0 24 24">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                          stroke-width="4" d="M6 18 17.94 6M18 18 6.06 6"></path>
                                </svg>
                            
                            </span>

                            <h3 class="stepper__item-title">Conclusão</h3>
                            <p class="text-sm">Poxa <b>{{ request.user.full_name }}</b>, dessa vez não foi, mas queremos
                                te ver novamente! Continue se
                                candidatando, seu talento é
                                incrível e certamente encontrará a oportunidade certa em breve.</p>

                        {% else %}

                            <span class="stepper__item stepper__item-default" id="step-4">
                            
                                <svg class="stepper__icon" aria-hidden="true"
                                     xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                                    <path d="M16 1h-3.278A1.992 1.992 0 0 0 11 0H7a1.993 1.993 0 0 0-1.722 1H2a2 2 0 0 0-2 2v15a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V3a2 2 0 0 0-2-2ZM7 2h4v3H7V2Zm5.7 8.289-3.975 3.857a1 1 0 0 1-1.393 0L5.3 12.182a1.002 1.002 0 1 1 1.4-1.436l1.328 1.289 3.28-3.181a1 1 0 1 1 1.392 1.435Z"></path>
                                </svg>
                            
                            </span>

                            <h3 class="stepper__item-title">Conclusão</h3>
                            <p class="text-sm">Aguarde enquanto avaliamos todo processo.</p>

                        {% endif %}


                    </li>

                </ol>

            </div>

            <div class="text-gray-500 text-sm text-center">
                <span>Candidatou-se em {{ application.application_date }}</span>
            </div>

            <button type="button" class="btn-disabled" id="remove_application" data-modal-target="remove_modal"
                    data-modal-toggle="remove_modal" disabled>
                Remover Candidatura
            </button>

        </div>

    </section>

    {% alert_modal id_modal='remove_modal' message='Deseja remover sua candidatura?' action_id='remove_action' %}

{% endblock %}



{% block js %}
    <script src="{% static 'src/js/stepper.js' %}"></script>
{% endblock %}

templates/candidates/applications/list.html
{% extends '_base.html' %}
{% block title %}Candidaturas{% endblock %}
{% load custom_tags %}

{% block content %}

    <div class="grid md:grid-cols-4 gap-4">

        {% for application in applications %}

            <a href="{% url 'core:application_detail' application.pk %}" class="box relative pb-6">

                <div class="box__content">

                    <div class="box__header">
                        <span class="text-sm"># {{ application.job.id_job }}</span>
                        <span class="{% if application.status == 'Não Selecionada' %} tag-danger {% else %} tag-success {% endif %}">{{ application.status }}</span>
                    </div>

                    <h1 class="box__title">
                        {{ application.job.title }}
                    </h1>

                    <p class="box__description text-sm">
                        {{ application.job.requirements | linebreaksbr }}
                    </p>

                    <p class="box__footer-date">{{ application.application_date }}</p>

                </div>

            </a>

        {% empty %}

            {% empty_list title='Nenhuma Candidatura' message='Suas cadidaturas aparecerão aqui' %}

        {% endfor %}

    </div>



{% endblock %}