JobsParana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.shortcuts import redirect
from django.urls import path

from core.views import JobListView, MyProfileView, MyCurriculumView, JobDetailView, \
    UserRegistrationView, MyAddressDetailView, MyQualificationsDetailView, MyExperienceDetailView, MyProfileDetailView, \
    MyApplicationDetailView, SearchView, MyExperienceListView, MyApplicationsListView, MyQualificationsListView

app_name = 'core'

urlpatterns = [
    path('', lambda request: redirect('core:jobs'), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('jobs/', JobListView.as_view(), name='jobs'),
    path('jobs/<pk>/detail/', JobDetailView.as_view(), name='job_detail'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('profile/registration/', UserRegistrationView.as_view(), name='registration'),
    path('curriculum/', MyCurriculumView.as_view(), name='curriculum'),
    path('curriculum/<pk>/profile/', MyProfileDetailView.as_view(), name='curriculum_profile'),
    path('curriculum/<pk>/address/', MyAddressDetailView.as_view(), name='curriculum_address'),
    path('curriculum/<id>/qualifications/', MyQualificationsListView.as_view(), name='curriculum_qualifications'),
    path('curriculum/qualifications/<pk>/detail/', MyQualificationsDetailView.as_view(),
         name='curriculum_qualifications_detail'),
    path('curriculum/<id>/experiences/', MyExperienceListView.as_view(), name='curriculum_experiences'),
    path('curriculum/experiences/<pk>/detail/', MyExperienceDetailView.as_view(),
         name='curriculum_experiences_detail'),
    path('applications/<id>/', MyApplicationsListView.as_view(), name='applications'),
    path('applications/<pk>/detail/', MyApplicationDetailView.as_view(), name='application_detail'),
]

templates/candidates/profile/address.html
{% extends '_base.html' %}
{% block title %} Endereço {% endblock %}
{% load custom_tags %}

{% block content %}



    <section class="bg-white p-4 shadow-md rounded-lg">

        <div class="container max-w-xl mx-auto">

            <form method="post" class="grid gap-6">
                {% csrf_token %}

                <div class="grid md:grid-cols-2 gap-4">
                    {% form_flowbite form %}
                </div>

                <button type="submit" class="btn-primary">
                    Salvar
                </button>

            </form>

        </div>

    </section>



{% endblock %}

templates/candidates/profile/index.html
{% extends '_base.html' %}

{% block content %}

    <div class="text-center pb-4">
        <p class="font-bold text-3xl ">{{ request.user.full_name }}</p>
        <p class="text-gray-400">{{ request.user.email }}</p>
    </div>

    <section class="grid md:grid-cols-2 gap-4 container mx-auto max-w-3xl">

        <a href="{% url 'core:curriculum_profile' request.user.id %}" class="bg-white shadow-md rounded-lg p-4">
            <div class="flex items-start justify-between">
                <h1 class="font-bold text-xl">Dados Pessoais</h1>

                <svg class="w-10 h-10 text-primary-100 dark:text-white" aria-hidden="true"
                     xmlns="http://www.w3.org/2000/svg"
                     fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd"
                          d="M4 4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H4Zm10 5a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm0 3a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm0 3a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm-8-5a3 3 0 1 1 6 0 3 3 0 0 1-6 0Zm1.942 4a3 3 0 0 0-2.847 2.051l-.044.133-.004.012c-.042.126-.055.167-.042.195.006.013.02.023.038.039.032.025.08.064.146.155A1 1 0 0 0 6 17h6a1 1 0 0 0 .811-.415.713.713 0 0 1 .146-.155c.019-.016.031-.026.038-.04.014-.027 0-.068-.042-.194l-.004-.012-.044-.133A3 3 0 0 0 10.059 14H7.942Z"
                          clip-rule="evenodd"></path>
                </svg>
                
            </div>

            <p class="font-light text-gray-400">Mantenha sempre seus dados pessoais atualizados.</p>

        </a>

        <a href="{% url 'core:curriculum_address' request.user.id %}" class="bg-white shadow-md rounded-lg p-4">
            <div class="flex items-start justify-between">
                <h1 class="font-bold text-xl">Endereço</h1>

                <svg class="w-10 h-10 text-primary-100" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                     fill="currentColor" viewBox="0 0 24 24">
                    <path fill-rule="evenodd"
                          d="M11.906 1.994a8.002 8.002 0 0 1 8.09 8.421 7.996 7.996 0 0 1-1.297 3.957.996.996 0 0 1-.133.204l-.108.129c-.178.243-.37.477-.573.699l-5.112 6.224a1 1 0 0 1-1.545 0L5.982 15.26l-.002-.002a18.146 18.146 0 0 1-.309-.38l-.133-.163a.999.999 0 0 1-.13-.202 7.995 7.995 0 0 1 6.498-12.518ZM15 9.997a3 3 0 1 1-5.999 0 3 3 0 0 1 5.999 0Z"
                          clip-rule="evenodd"></path>
                </svg>
                
            </div>

            <p class="font-light text-gray-400">Informe seu endereço para completar o cadastro.</p>

        </a>

        <a href="{% url 'core:curriculum_experiences' request.user.id %}" class="bg-white shadow-md rounded-lg p-4">
            <div class="flex items-start justify-between">
                <h1 class="font-bold text-xl">Experiências</h1>

                <svg class="w-10 h-10 text-primary-100" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                     fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 7.205c4.418 0 8-1.165 8-2.602C20 3.165 16.418 2 12 2S4 3.165 4 4.603c0 1.437 3.582 2.602 8 2.602ZM12 22c4.963 0 8-1.686 8-2.603v-4.404c-.052.032-.112.06-.165.09a7.75 7.75 0 0 1-.745.387c-.193.088-.394.173-.6.253-.063.024-.124.05-.189.073a18.934 18.934 0 0 1-6.3.998c-2.135.027-4.26-.31-6.3-.998-.065-.024-.126-.05-.189-.073a10.143 10.143 0 0 1-.852-.373 7.75 7.75 0 0 1-.493-.267c-.053-.03-.113-.058-.165-.09v4.404C4 20.315 7.037 22 12 22Zm7.09-13.928a9.91 9.91 0 0 1-.6.253c-.063.025-.124.05-.189.074a18.935 18.935 0 0 1-6.3.998c-2.135.027-4.26-.31-6.3-.998-.065-.024-.126-.05-.189-.074a10.163 10.163 0 0 1-.852-.372 7.816 7.816 0 0 1-.493-.268c-.055-.03-.115-.058-.167-.09V12c0 .917 3.037 2.603 8 2.603s8-1.686 8-2.603V7.596c-.052.031-.112.059-.165.09a7.816 7.816 0 0 1-.745.386Z"></path>
                </svg>
                
            </div>

            <p class="font-light text-gray-400">Adicione suas experiências anteriores e fortaleça sua candidatura.</p>

        </a>

        <a href="{% url 'core:curriculum_qualifications' request.user.id %}" class="bg-white shadow-md rounded-lg p-4">
            <div class="flex items-start justify-between">
                <h1 class="font-bold text-xl">Qualificações</h1>

                <svg class="w-10 h-10 text-primary-100" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                     fill="currentColor" viewBox="0 0 24 24">
                    <path d="M11 9a1 1 0 1 1 2 0 1 1 0 0 1-2 0Z"></path>
                    <path fill-rule="evenodd"
                          d="M9.896 3.051a2.681 2.681 0 0 1 4.208 0c.147.186.38.282.615.255a2.681 2.681 0 0 1 2.976 2.975.681.681 0 0 0 .254.615 2.681 2.681 0 0 1 0 4.208.682.682 0 0 0-.254.615 2.681 2.681 0 0 1-2.976 2.976.681.681 0 0 0-.615.254 2.682 2.682 0 0 1-4.208 0 .681.681 0 0 0-.614-.255 2.681 2.681 0 0 1-2.976-2.975.681.681 0 0 0-.255-.615 2.681 2.681 0 0 1 0-4.208.681.681 0 0 0 .255-.615 2.681 2.681 0 0 1 2.976-2.975.681.681 0 0 0 .614-.255ZM12 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"
                          clip-rule="evenodd"></path>
                    <path d="M5.395 15.055 4.07 19a1 1 0 0 0 1.264 1.267l1.95-.65 1.144 1.707A1 1 0 0 0 10.2 21.1l1.12-3.18a4.641 4.641 0 0 1-2.515-1.208 4.667 4.667 0 0 1-3.411-1.656Zm7.269 2.867 1.12 3.177a1 1 0 0 0 1.773.224l1.144-1.707 1.95.65A1 1 0 0 0 19.915 19l-1.32-3.93a4.667 4.667 0 0 1-3.4 1.642 4.643 4.643 0 0 1-2.53 1.21Z"></path>
                </svg>
                
            </div>

            <p class="font-light text-gray-400">Cadastre suas qualificações e destaque seu potencial.</p>

        </a>

    </section>

{% endblock %}

templates/candidates/profile/profile.html
{% extends '_base.html' %}
{% block title %} Dados Pessoais {% endblock %}
{% load custom_tags %}
{% load static %}

{% block content %}

    <section class="bg-white p-4 shadow-md rounded-lg">

        <div class="container max-w-lg mx-auto">

            <form method="post" class="grid gap-4">
                {% csrf_token %}

                {% form_flowbite form_profile %}
                {% form_flowbite form_curriculum %}

                <button type="submit" class="btn-primary">
                    Salvar
                </button>

            </form>

        </div>

    </section>

{% endblock %}