JobsParana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.shortcuts import redirect
from django.urls import path

from core.views import JobListView, MyProfileView, MyCurriculumView, JobDetailView, \
    UserRegistrationView, MyAddressDetailView, MyQualificationsDetailView, MyExperienceDetailView, MyProfileDetailView, \
    MyApplicationDetailView, SearchView, MyExperienceListView, MyApplicationsListView, MyQualificationsListView

app_name = 'core'

urlpatterns = [
    path('', lambda request: redirect('core:jobs'), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('jobs/', JobListView.as_view(), name='jobs'),
    path('jobs/<pk>/detail/', JobDetailView.as_view(), name='job_detail'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('profile/registration/', UserRegistrationView.as_view(), name='registration'),
    path('curriculum/', MyCurriculumView.as_view(), name='curriculum'),
    path('curriculum/<pk>/profile/', MyProfileDetailView.as_view(), name='curriculum_profile'),
    path('curriculum/<pk>/address/', MyAddressDetailView.as_view(), name='curriculum_address'),
    path('curriculum/<id>/qualifications/', MyQualificationsListView.as_view(), name='curriculum_qualifications'),
    path('curriculum/qualifications/<pk>/detail/', MyQualificationsDetailView.as_view(),
         name='curriculum_qualifications_detail'),
    path('curriculum/<id>/experiences/', MyExperienceListView.as_view(), name='curriculum_experiences'),
    path('curriculum/experiences/<pk>/detail/', MyExperienceDetailView.as_view(),
         name='curriculum_experiences_detail'),
    path('applications/<id>/', MyApplicationsListView.as_view(), name='applications'),
    path('applications/<pk>/detail/', MyApplicationDetailView.as_view(), name='application_detail'),
]

templates/misc/navbar.html
{% load static %}
{% load custom_tags %}

<nav class="fixed top-0 z-40 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
    <div class="px-3 py-3">
        <div class="flex items-center justify-between">

            <div class="w-[30px] block md:hidden">
                <img src="{% static 'imgs/brasao_parana.svg' %}" class="h-10" alt="Brasao Parana"/>
            </div>

            <div class="text-sm">
                {% include 'misc/logo_agencia_trabalhador.html' %}
            </div>

            <div class="flex items-center">

                <div class="flex items-center">

                    <div>
                        <button type="button"
                                aria-expanded="false" data-dropdown-toggle="dropdown-user">
                            <span class="sr-only">Open user menu</span>

                            <svg class="w-[30px] h-[30px] text-gray-800 dark:text-white" aria-hidden="true"
                                 xmlns="http://www.w3.org/2000/svg" fill="none"
                                 viewBox="0 0 24 24">
                                <path stroke="currentColor" stroke-linecap="round" stroke-width="4"
                                      d="M12 6h.01M12 12h.01M12 18h.01"></path>
                            </svg>

                        </button>
                    </div>

                    <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600"
                         id="dropdown-user">

                        <div class="px-4 py-3" role="none">
                            <p class="text-sm text-gray-900 dark:text-white" role="none">
                                {{ request.user.full_name }}
                            </p>
                            <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                                {{ request.user.email }}
                            </p>
                        </div>

                        <ul class="py-1" role="none">

                            <li>
                                <a href="#"
                                   class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
                                   role="menuitem">Trocar Senha</a>
                            </li>

                            <li>
                                <a href="#"
                                   class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
                                   role="menuitem">Ajustes</a>
                            </li>

                            <li>
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button type="submit"
                                            class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white"
                                            role="menuitem">Logout
                                    </button>
                                </form>

                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

<aside
       class="fixed top-0 left-0 z-30 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700"
       aria-label="Sidebar">

    <div class="h-full px-3 pb-4 overflow-y-auto bg-white dark:bg-gray-800">

        <ul class="space-y-2 font-medium">

            <li>
                <a href="{% url 'core:search' %}"
                   class="{% path_name_css request.path 'search' default='text-gray-500' selected='text-primary-100 bg-gray-50' %} flex items-center p-2 rounded-lg group">
                    <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         width="26" height="26" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-width="2"
                              d="m21 21-3.5-3.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z"></path>
                    </svg>
                    <span class="ms-3">Buscar</span>
                </a>
            </li>

            <li>
                <a href="{% url 'core:jobs' %}"
                   class="{% path_name_css request.path 'jobs' default='text-gray-500' selected='text-primary-100 bg-gray-50' %} flex items-center p-2 rounded-lg group">
                    <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         width="26" height="26" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4.857 3A1.857 1.857 0 0 0 3 4.857v4.286C3 10.169 3.831 11 4.857 11h4.286A1.857 1.857 0 0 0 11 9.143V4.857A1.857 1.857 0 0 0 9.143 3H4.857Zm10 0A1.857 1.857 0 0 0 13 4.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 21 9.143V4.857A1.857 1.857 0 0 0 19.143 3h-4.286Zm-10 10A1.857 1.857 0 0 0 3 14.857v4.286C3 20.169 3.831 21 4.857 21h4.286A1.857 1.857 0 0 0 11 19.143v-4.286A1.857 1.857 0 0 0 9.143 13H4.857ZM18 14a1 1 0 1 0-2 0v2h-2a1 1 0 1 0 0 2h2v2a1 1 0 1 0 2 0v-2h2a1 1 0 1 0 0-2h-2v-2Z"
                              clip-rule="evenodd"></path>
                    </svg>
                    <span class="ms-3">Vagas</span>
                </a>
            </li>

            <li>
                <a href="{% url 'core:applications' request.user.id %}"
                   class="{% path_name_css request.path 'applications' default='text-gray-500' selected='text-primary-100 bg-gray-50' %} flex items-center p-2 rounded-lg group">
                    <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         width="26" height="26" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M20.337 3.664c.213.212.354.486.404.782.294 1.711.657 5.195-.906 6.76-1.77 1.768-8.485 5.517-10.611 6.683a.987.987 0 0 1-1.176-.173l-.882-.88-.877-.884a.988.988 0 0 1-.173-1.177c1.165-2.126 4.913-8.841 6.682-10.611 1.562-1.563 5.046-1.198 6.757-.904.296.05.57.191.782.404ZM5.407 7.576l4-.341-2.69 4.48-2.857-.334a.996.996 0 0 1-.565-1.694l2.112-2.111Zm11.357 7.02-.34 4-2.111 2.113a.996.996 0 0 1-1.69-.565l-.422-2.807 4.563-2.74Zm.84-6.21a1.99 1.99 0 1 1-3.98 0 1.99 1.99 0 0 1 3.98 0Z"
                              clip-rule="evenodd"></path>
                    </svg>
                    <span class="flex-1 ms-3 whitespace-nowrap">Candidaturas</span>
                </a>
            </li>

            <li>
                <a href="{% url 'core:curriculum' %}"
                   class="{% path_name_css request.path 'curriculum' default='text-gray-500' selected='text-primary-100 bg-gray-50' %} flex items-center p-2 rounded-lg group">

                    <svg aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor"
                         viewBox="0 0 24 24">
                        <path fill-rule="evenodd"
                              d="M4 4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H4Zm10 5a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm0 3a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm0 3a1 1 0 0 1 1-1h3a1 1 0 1 1 0 2h-3a1 1 0 0 1-1-1Zm-8-5a3 3 0 1 1 6 0 3 3 0 0 1-6 0Zm1.942 4a3 3 0 0 0-2.847 2.051l-.044.133-.004.012c-.042.126-.055.167-.042.195.006.013.02.023.038.039.032.025.08.064.146.155A1 1 0 0 0 6 17h6a1 1 0 0 0 .811-.415.713.713 0 0 1 .146-.155c.019-.016.031-.026.038-.04.014-.027 0-.068-.042-.194l-.004-.012-.044-.133A3 3 0 0 0 10.059 14H7.942Z"
                              clip-rule="evenodd"></path>
                    </svg>

                    <span class="flex-1 ms-3 whitespace-nowrap">Currículo</span>
                </a>
            </li>

        </ul>
    </div>
</aside>