JobsParana/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls', namespace='core')),
]

core/urls.py
from django.shortcuts import redirect
from django.urls import path

from core.views import JobListView, MyProfileView, MyCurriculumView, JobDetailView, \
    UserRegistrationView, MyAddressDetailView, MyQualificationsDetailView, MyExperienceDetailView, MyProfileDetailView, \
    MyApplicationDetailView, SearchView, MyExperienceListView, MyApplicationsListView, MyQualificationsListView

app_name = 'core'

urlpatterns = [
    path('', lambda request: redirect('core:jobs'), name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('jobs/', JobListView.as_view(), name='jobs'),
    path('jobs/<pk>/detail/', JobDetailView.as_view(), name='job_detail'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('profile/registration/', UserRegistrationView.as_view(), name='registration'),
    path('curriculum/', MyCurriculumView.as_view(), name='curriculum'),
    path('curriculum/<pk>/profile/', MyProfileDetailView.as_view(), name='curriculum_profile'),
    path('curriculum/<pk>/address/', MyAddressDetailView.as_view(), name='curriculum_address'),
    path('curriculum/<id>/qualifications/', MyQualificationsListView.as_view(), name='curriculum_qualifications'),
    path('curriculum/qualifications/<pk>/detail/', MyQualificationsDetailView.as_view(),
         name='curriculum_qualifications_detail'),
    path('curriculum/<id>/experiences/', MyExperienceListView.as_view(), name='curriculum_experiences'),
    path('curriculum/experiences/<pk>/detail/', MyExperienceDetailView.as_view(),
         name='curriculum_experiences_detail'),
    path('applications/<id>/', MyApplicationsListView.as_view(), name='applications'),
    path('applications/<pk>/detail/', MyApplicationDetailView.as_view(), name='application_detail'),
]

templates/candidates/jobs/detail.html
{% extends '_base.html' %}
{% load custom_tags %}
{% block title %}
    {{ job.title }}
{% endblock %}

{% block content %}

    <section class="grid gap-4 bg-white p-4 rounded-lg shadow-md">

        <div class="flex justify-between items-center w-full space-x-2">

            <p class="text-gray-400"># {{ job.id_job }}</p>

            <div class="text-red-600 font-semibold ml-auto space-x-1 text-sm">

                {% if job.is_pcd %}
                    <span class="tag-danger">Exclusivo PCD</span>
                {% endif %}

                {% if job.is_urgent %}
                    <span class="tag-danger">Urgente</span>
                {% endif %}

            </div>

        </div>

        <div class="container mx-auto max-w-2xl space-y-6">

            <div class="space-y-1">

                <div class="flex items-center space-x-2">

                    <svg class="w-5 h-5 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         fill="none" viewBox="0 0 21 21">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.2"
                              d="m7.171 12.906-2.153 6.411 2.672-.89 1.568 2.34 1.825-5.183m5.73-2.678 2.154 6.411-2.673-.89-1.568 2.34-1.825-5.183M9.165 4.3c.58.068 1.153-.17 1.515-.628a1.681 1.681 0 0 1 2.64 0 1.68 1.68 0 0 0 1.515.628 1.681 1.681 0 0 1 1.866 1.866c-.068.58.17 1.154.628 1.516a1.681 1.681 0 0 1 0 2.639 1.682 1.682 0 0 0-.628 1.515 1.681 1.681 0 0 1-1.866 1.866 1.681 1.681 0 0 0-1.516.628 1.681 1.681 0 0 1-2.639 0 1.681 1.681 0 0 0-1.515-.628 1.681 1.681 0 0 1-1.867-1.866 1.681 1.681 0 0 0-.627-1.515 1.681 1.681 0 0 1 0-2.64c.458-.361.696-.935.627-1.515A1.681 1.681 0 0 1 9.165 4.3ZM14 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"></path>
                    </svg>

                    <p class="font-bold">Requisitos</p>
                </div>

                <div class="rounded-lg border border-gray-100 bg-gray-50 ml-7 p-2">
                    {{ job.requirements | linebreaks }}
                </div>

            </div>

            <div class="space-y-1">

                <div class="flex items-center space-x-2">

                    <svg class="w-5 h-5 text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                              d="M17 8H5m12 0a1 1 0 0 1 1 1v2.6M17 8l-4-4M5 8a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.6M5 8l4-4 4 4m6 4h-4a2 2 0 1 0 0 4h4a1 1 0 0 0 1-1v-2a1 1 0 0 0-1-1Z"></path>
                    </svg>

                    <p class="font-bold">Benefícios</p>
                </div>

                <div class="rounded-lg border border-gray-100 bg-gray-50 ml-7 p-2">
                    {{ job.benefits | linebreaks }}
                </div>

            </div>

            <div class="space-y-1">

                <div class="flex items-center space-x-2">

                    <svg class="w-5 h-5 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         width="24" height="24" fill="none" viewBox="0 0 24 24">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                              d="M12 8v4l3 3m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"></path>
                    </svg>

                    <p class="font-bold">Horário</p>
                </div>

                <div class="rounded-lg border border-gray-100 bg-gray-50 ml-7 p-2">
                    {{ job.time_scale }}
                </div>

            </div>

            <div class="space-y-1">

                <div class="flex items-center space-x-2">

                    <svg class="w-5 h-5 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                         fill="none" viewBox="0 0 22 22">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                              d="M12 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"></path>
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                              d="M17.8 13.938h-.011a7 7 0 1 0-11.464.144h-.016l.14.171c.1.127.2.251.3.371L12 21l5.13-6.248c.194-.209.374-.429.54-.659l.13-.155Z"></path>
                    </svg>

                    <p class="font-bold">Local de trabalho</p>
                </div>

                <div class="rounded-lg border border-gray-100 bg-gray-50 ml-7 p-2">
                    {{ job.company.district }} - {{ job.company.city }}
                </div>

            </div>

            <div class="space-y-1">

                <div class="flex items-center space-x-2">

                    <svg class="w-5 h-5 text-gray-400" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 22 22">
                        <path stroke="currentColor" stroke-linecap="round" stroke-width="1.7"
                              d="M8 7V6a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-1M3 18v-7a1 1 0 0 1 1-1h11a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1Zm8-3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0Z"></path>
                    </svg>

                    <p class="font-bold">Remuneração</p>
                </div>

                <div class="rounded-lg border border-gray-100 bg-gray-50 ml-7 p-2">
                    R$ {{ job.remuneration }}
                </div>

            </div>

        </div>

        <div class="grid mx-auto max-w-sm container">

            {% if is_already %}

                <span class="tag-success-large">Você já se candidatou</span>

            {% else %}

                <button data-modal-target="confirm_modal" data-modal-toggle="confirm_modal" class="btn-primary"
                        type="button">
                    Quero me candidatar
                </button>


            {% endif %}

        </div>


    </section>

    {% if not is_already %}

        {% alert_modal id_modal='confirm_modal' message='Confirmar candidatura?' action_id='confirm_action' %}

    {% endif %}


{% endblock %}

templates/candidates/jobs/list.html
{% extends '_base.html' %}
{% load custom_tags %}
{% block title %}

    <div class="main__title-search">

        <span>Últimas Vagas</span>

        <form class="md:w-2/4" id="search">

            <label for="search-input"
                   class="input__search-label">Buscar</label>

            <div class="input__search-container">

                <div class="input__search-icon-container">

                    <svg class="input__search-icon" aria-hidden="true"
                         xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"></path>
                    </svg>

                </div>

                <input type="search" name="search" id="search-input"
                       class="input__search"
                       placeholder="Buscar vagas" required/>

                <button type="submit"
                        class="btn__search-primary">
                    Buscar
                </button>

            </div>

        </form>

    </div>



{% endblock title %}

{% block content %}

    <section class="grid md:grid-cols-3 gap-4">

        {% for job in page_obj %}

            <a href="{% url 'core:job_detail' job.id %}"
               class="flex flex-row bg-white rounded-lg shadow-md select-none">

                <div class="grid gap-2 p-4 w-full">

                    <div class="flex text-sm">

                        <span class="text-gray-400"># {{ job.id_job }}</span>

                        <div class="text-red-600 font-semibold ml-auto space-x-1">

                            {% if job.is_pcd %}
                                <span class="px-2 py-0.5 bg-red-100 rounded-full">Exclusivo PCD</span>
                            {% endif %}

                            {% if job.is_urgent %}
                                <span class="px-2 py-0.5 bg-red-100 rounded-full">Urgente</span>
                            {% endif %}

                        </div>

                    </div>

                    <p class="text-2xl font-bold">{{ job.title }}</p>
                    <p class="text-xl font-bold text-primary-100">R$ {{ job.remuneration }}</p>

                    <div>
                        <p class="text-lg font-semibold">Requisitos</p>
                        <span class="text-sm line-clamp-3">{{ job.requirements | linebreaksbr }}</span>
                    </div>

                    <div class="flex items-center space-x-1.5 mt-auto">

                        <svg class="w-4 h-4 text-red-600" aria-hidden="true"
                             xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                             viewBox="0 0 24 24">
                            <path fill-rule="evenodd"
                                  d="M11.906 1.994a8.002 8.002 0 0 1 8.09 8.421 7.996 7.996 0 0 1-1.297 3.957.996.996 0 0 1-.133.204l-.108.129c-.178.243-.37.477-.573.699l-5.112 6.224a1 1 0 0 1-1.545 0L5.982 15.26l-.002-.002a18.146 18.146 0 0 1-.309-.38l-.133-.163a.999.999 0 0 1-.13-.202 7.995 7.995 0 0 1 6.498-12.518ZM15 9.997a3 3 0 1 1-5.999 0 3 3 0 0 1 5.999 0Z"
                                  clip-rule="evenodd" stroke="3"></path>
                        </svg>

                        <p class="text-sm ">{{ job.company.city }} - {{ job.company.district }}</p>

                    </div>

                    <p class="text-xs text-gray-400 mt-auto">Válido até - {{ job.end_registration_date | date }}

                </div>

            </a>
        {% empty %}

            {% empty_list title='Nenhuma vaga disponível' message='Breve novas oportunidades' %}

        {% endfor %}

    </section>

{% endblock %}